/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
        soviet: ['"Russo One"', '"Unbounded"', 'sans-serif'],
        russo: ['"Russo One"', 'sans-serif'],
        space: ['"Space Mono"', '"Share Tech Mono"', 'monospace'],
        telemetry: ['"Space Mono"', '"Share Tech Mono"', '"JetBrains Mono"', 'monospace'],
        orbitron: ['"Orbitron"', '"Unbounded"', 'sans-serif'],
        unbounded: ['"Unbounded"', '"Russo One"', 'sans-serif'],
        cinzel: ['"Russo One"', '"Unbounded"', 'sans-serif'],
        garamond: ['"Space Mono"', 'monospace'],
        marcellus: ['"Russo One"', 'sans-serif'],
        alchemical: ['"Russo One"', 'sans-serif'],
        cartography: ['"Russo One"', 'sans-serif'],
        constructivist: ['"Russo One"', 'sans-serif'],
        edo: ['"Russo One"', '"Unbounded"', 'sans-serif'],
        mincho: ['"Space Mono"', 'monospace'],
        yuji: ['"Russo One"', 'sans-serif'],
        blueprint: ['"Space Mono"', 'monospace'],
        display: ['"Russo One"', '"Orbitron"', 'sans-serif'],
        cormorant: ['"Space Mono"', 'monospace'],
        oldstandard: ['"Space Mono"', 'monospace'],
        vintagemono: ['"Space Mono"', 'monospace'],
        sans: ['"Space Mono"', 'sans-serif'],
        konstrukt: ['"Russo One"', 'sans-serif'],
        blueprintmono: ['"Space Mono"', 'monospace'],
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        edo: {
          lacquer: '#121820',
          lacquerDark: '#0a0e14',
          lacquerLight: '#18222e',
          washi: '#f4ecd8',
          washiLight: '#fbf6eb',
          washiAged: '#e8dcbe',
          sumi: '#1a1412',
          sumiMuted: '#5c4e46',
          indigo: '#1b3a5c',
          indigoDark: '#12263d',
          indigoLight: '#2c5685',
          vermilion: '#9e2a2b',
          vermilionDark: '#7f1d1d',
          vermilionLight: '#c53030',
          gold: '#c4952a',
          goldLight: '#e5b84c',
          goldDark: '#8a6516',
          pine: '#2d5046',
          pineLight: '#3d6b5e',
        },
        alchemical: {
          abyss: '#061019',
          abyssDark: '#03080d',
          abyssLight: '#0c1b2a',
          parchment: '#f3ebd9',
          parchmentLight: '#fbf7ee',
          parchmentAged: '#e8dcbe',
          parchmentDark: '#121e2c',
          gold: '#d4af37',
          goldLight: '#f3e5ab',
          goldDark: '#8c6d1f',
          bronze: '#c59b27',
          ink: '#24160a',
          inkMuted: '#6b5c4d',
          inkIndigo: '#0e2a47',
          waxRed: '#991b1b',
          waxGold: '#b45309',
        },
        blueprint: {
          base: '#061019',
          baseDark: '#03080d',
          baseLight: '#0c1b2a',
          paper: '#f3ebd9',
          paperLight: '#fbf7ee',
          cyan: '#d4af37',
          cyanGlow: '#c59b27',
          red: '#991b1b',
          redDark: '#7f1d1d',
          yellow: '#d4af37',
          steel: '#121e2c',
          grid: 'rgba(212, 175, 55, 0.15)',
          ink: '#24160a',
          inkMuted: '#6b5c4d',
        },
        cartel: {
          felt: '#081220',
          feltDark: '#040a14',
          feltLight: '#0e1d33',
          paper: '#eae4d5',
          paperAged: '#ded7c4',
          paperDark: '#132137',
          brass: '#38bdf8',
          brassLight: '#7dd3fc',
          brassDark: '#0284c7',
          brassBorder: '#0369a1',
          ink: '#0b0f19',
          inkCharcoal: '#1e293b',
          inkMuted: '#64748b',
          carmine: '#dc2626',
          oxblood: '#991b1b',
          prussian: '#1d4ed8',
          emerald: '#059669',
          ochre: '#d97706',
          terracotta: '#ea580c',
          amethyst: '#7c3aed',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'stamp-slam': {
          '0%': { transform: 'scale(2.2) rotate(-14deg)', opacity: '0' },
          '60%': { transform: 'scale(0.95) rotate(-6deg)', opacity: '1' },
          '80%': { transform: 'scale(1.05) rotate(-7.5deg)' },
          '100%': { transform: 'scale(1) rotate(-7deg)', opacity: '1' },
        },
        'bill-slide': {
          '0%': { transform: 'translateY(-10px) opacity(0)' },
          '100%': { transform: 'translateY(0) opacity(1)' },
        }
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'stamp': 'stamp-slam 0.35s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards',
      },
    },
  },
  plugins: [],
};
