/**
 * Board configuration for "Офисный планктон: Корпоративная жизнь" (40 tiles & 24 tiles)
 */

const BOARD_TILES_OFFICE_40 = [
  // --- BOTTOM ROW (Tiles 0 to 10) ---
  {
    id: 0,
    name: 'ДЕНЬ ЗАРПЛАТЫ',
    type: 'start',
    description: 'Зарплата упала на карту! Получите призовые +200 ₽ при прохождении круга',
    bonus: 200,
    icon: '💳',
    iconUrl: '/assets/tiles/office/start_payday.png'
  },
  {
    id: 1,
    name: 'Строгий вахтёр',
    type: 'property',
    group: 'brown',
    groupName: 'Входная группа & Стажировка',
    color: '#8D6E63',
    price: 60,
    housePrice: 50,
    mortgageValue: 30,
    rents: [10, 30, 90, 270, 400, 550],
    icon: '🛂',
    iconUrl: '/assets/tiles/office/security_turnstile.png',
    description: '«Где ваш пропуск?» Строгий вахтёр со сканером СКУД и чаем в граненом стакане.'
  },
  {
    id: 2,
    name: 'Корпоративная Казна',
    type: 'chest',
    description: 'Премиальный фонд и 13-я зарплата. Тяните карту выплат и корпоративных бонусов',
    icon: '🎁',
    iconUrl: '/assets/tiles/office/chest_bonus.png'
  },
  {
    id: 3,
    name: 'Стажёр с кофе',
    type: 'property',
    group: 'brown',
    groupName: 'Входная группа & Стажировка',
    color: '#8D6E63',
    price: 80,
    housePrice: 50,
    mortgageValue: 40,
    rents: [14, 40, 120, 360, 500, 650],
    icon: '📋',
    iconUrl: '/assets/tiles/office/intern_stack.png',
    description: 'Балансирует шаткую стопку отчётов А4 и стаканчики кофе, молясь не споткнуться в коридоре.'
  },
  {
    id: 4,
    name: 'Штраф за опоздание',
    type: 'tax',
    amount: 200,
    description: 'Опоздание на 1 минуту в 09:01! Заплатите штраф 200 ₽ в фонд дисциплины',
    icon: '⏱️',
    iconUrl: '/assets/tiles/office/tax_late.png'
  },
  {
    id: 5,
    name: 'Шаттл от метро',
    type: 'property',
    group: 'transport',
    groupName: 'Офисная логистика',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🚐',
    iconUrl: '/assets/tiles/office/metro_shuttle.png',
    description: 'Утренний микроавтобус до бизнес-центра. Битва за свободные сидячие места в час пик.'
  },
  {
    id: 6,
    name: 'Сплетница у кулера',
    type: 'property',
    group: 'lightblue',
    groupName: 'Кофе-поинт & Кухня',
    color: '#29B6F6',
    price: 100,
    housePrice: 50,
    mortgageValue: 50,
    rents: [18, 50, 150, 450, 625, 750],
    icon: '💧',
    iconUrl: '/assets/tiles/office/cooler_gossip.png',
    description: 'Знает всё о премиях, сокращениях и романах в опенспейсе раньше самого генерального директора.'
  },
  {
    id: 7,
    name: 'Служебный шанс',
    type: 'chance',
    description: 'Оффер от конкурентов, внезапная проверка или карьерный взлёт. Тяните карту «Шанс»!',
    icon: '💼',
    iconUrl: '/assets/tiles/office/chance_offer.png'
  },
  {
    id: 8,
    name: 'Коллега с рыбой',
    type: 'property',
    group: 'lightblue',
    groupName: 'Кофе-поинт & Кухня',
    color: '#29B6F6',
    price: 100,
    housePrice: 50,
    mortgageValue: 50,
    rents: [18, 50, 150, 450, 625, 750],
    icon: '🐟',
    iconUrl: '/assets/tiles/office/fish_microwave.png',
    description: 'Разогрел минтай с чесноком ровно в 13:00, несмотря на табличку «РЫБУ НЕ ГРЕТЬ!». Запах на весь этаж.'
  },
  {
    id: 9,
    name: 'Секретарша',
    type: 'property',
    group: 'lightblue',
    groupName: 'Кофе-поинт & Кухня',
    color: '#29B6F6',
    price: 120,
    housePrice: 50,
    mortgageValue: 60,
    rents: [22, 60, 180, 500, 700, 900],
    icon: '☕',
    iconUrl: '/assets/tiles/office/coffee_machine.png',
    description: 'Повелительница двойного эспрессо. Единственная, кто знает, куда нажать при ошибке «Fill Water Tank».'
  },
  {
    id: 10,
    name: 'ДУШНЫЙ КУБИКЛ',
    type: 'jail',
    description: 'Штрафной стол прямо за бетонной колонной без окон. Только посещение или отработка штрафа',
    icon: '🧱',
    iconUrl: '/assets/tiles/office/penalty_cubicle.png'
  },

  // --- LEFT ROW (Tiles 11 to 20) ---
  {
    id: 11,
    name: 'HR-интервью',
    type: 'property',
    group: 'pink',
    groupName: 'HR & Корпоративная культура',
    color: '#EC407A',
    price: 140,
    housePrice: 100,
    mortgageValue: 70,
    rents: [26, 70, 200, 550, 750, 950],
    icon: '📋',
    iconUrl: '/assets/tiles/office/hr_interview.png',
    description: '«Кем вы видите себя в компании через 5 лет?» Сканирует резюме рентгеновским взглядом.'
  },
  {
    id: 12,
    name: 'Техподдержка',
    type: 'property',
    group: 'utility',
    groupName: 'Сервисные службы офиса',
    color: '#8D6E63',
    price: 150,
    mortgageValue: 75,
    rents: [20, 60, 120, 240],
    icon: '🔌',
    iconUrl: '/assets/tiles/office/it_helpdesk.png',
    description: 'Ползает под столами в клубках кабелей с коронной фразой: «А вы пробовали выключить и включить?».'
  },
  {
    id: 13,
    name: 'Бизнес-коуч',
    type: 'property',
    group: 'pink',
    groupName: 'HR & Корпоративная культура',
    color: '#EC407A',
    price: 140,
    housePrice: 100,
    mortgageValue: 70,
    rents: [26, 70, 200, 550, 750, 950],
    icon: '📢',
    iconUrl: '/assets/tiles/office/business_coach.png',
    description: 'Рисует стрелы взрывного роста на флипчарте и учит выходить из зоны комфорта за счёт компании.'
  },
  {
    id: 14,
    name: 'Пятничная пицца',
    type: 'property',
    group: 'pink',
    groupName: 'HR & Корпоративная культура',
    color: '#EC407A',
    price: 160,
    housePrice: 100,
    mortgageValue: 80,
    rents: [30, 80, 220, 600, 800, 1000],
    icon: '🍕',
    iconUrl: '/assets/tiles/office/friday_party.png',
    description: 'Пятница 18:00! Несёт стопку коробок с горячей пиццей, галстук повязан на лоб, впереди тимбилдинг.'
  },
  {
    id: 15,
    name: 'Лифт в час пик',
    type: 'property',
    group: 'transport',
    groupName: 'Офисная логистика',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🛗',
    iconUrl: '/assets/tiles/office/elevator_crowd.png',
    description: '«Пропустите, мне на 42-й!» Толпа набита как сельди в бочке под мигающей лампочкой «ПЕРЕГРУЗ».'
  },
  {
    id: 16,
    name: 'Сейлз с гонгом',
    type: 'property',
    group: 'orange',
    groupName: 'Отдел продаж & Бухгалтерия',
    color: '#FFA726',
    price: 180,
    housePrice: 100,
    mortgageValue: 90,
    rents: [34, 90, 250, 700, 875, 1050],
    icon: '🔔',
    iconUrl: '/assets/tiles/office/sales_gong.png',
    description: 'Яростно звонит в латунный гонг закрытой сделки, размахивая свежеподписанным договором на миллион.'
  },
  {
    id: 17,
    name: 'Корпоративная Казна',
    type: 'chest',
    description: 'Тяните карту квартального бонуса или приказа о внеочередном премировании',
    icon: '🎁',
    iconUrl: '/assets/tiles/office/chest_bonus.png'
  },
  {
    id: 18,
    name: 'Стресс-бухгалтер',
    type: 'property',
    group: 'orange',
    groupName: 'Отдел продаж & Бухгалтерия',
    color: '#FFA726',
    price: 180,
    housePrice: 100,
    mortgageValue: 90,
    rents: [34, 90, 250, 700, 875, 1050],
    icon: '🧮',
    iconUrl: '/assets/tiles/office/stressed_accountant.png',
    description: 'Забаррикадировалась стеной синих папок «Корона», лихорадочно выбивая баланс на калькуляторе.'
  },
  {
    id: 19,
    name: 'Главбух Римма',
    type: 'property',
    group: 'orange',
    groupName: 'Отдел продаж & Бухгалтерия',
    color: '#FFA726',
    price: 200,
    housePrice: 100,
    mortgageValue: 100,
    rents: [38, 100, 300, 750, 925, 1100],
    icon: '☕',
    iconUrl: '/assets/tiles/office/chief_accountant.png',
    description: 'Властная хозяйка всех счетов и реестров. Неторопливо пьёт чай с пряниками, пока весь отдел трепещет.'
  },
  {
    id: 20,
    name: 'ВЫГОРАНИЕ В ЛАУНДЖЕ',
    type: 'free_parking',
    description: 'Мягкий пуфик под комнатным фикусом. Бесплатный отдых от созвонов и медитация под кондиционером',
    icon: '🛋️',
    iconUrl: '/assets/tiles/office/lounge_burnout.png'
  },

  // --- TOP ROW (Tiles 21 to 30) ---
  {
    id: 21,
    name: 'Дежурный админ',
    type: 'property',
    group: 'red',
    groupName: 'IT-департамент & Dev',
    color: '#EF5350',
    price: 220,
    housePrice: 150,
    mortgageValue: 110,
    rents: [42, 110, 330, 800, 975, 1150],
    icon: '🚨',
    iconUrl: '/assets/tiles/office/devops_alert.png',
    description: 'Спит в худи на офисном диване, но мгновенно подрывается при звуке сирены падения продакшна.'
  },
  {
    id: 22,
    name: 'Служебный шанс',
    type: 'chance',
    description: 'Тяните карту служебных неожиданностей, дедлайнов и аудиторских проверок',
    icon: '💼',
    iconUrl: '/assets/tiles/office/chance_offer.png'
  },
  {
    id: 23,
    name: 'Фронтендер и CSS',
    type: 'property',
    group: 'red',
    groupName: 'IT-департамент & Dev',
    color: '#EF5350',
    price: 220,
    housePrice: 150,
    mortgageValue: 110,
    rents: [42, 110, 330, 800, 975, 1150],
    icon: '💻',
    iconUrl: '/assets/tiles/office/frontend_css.png',
    description: 'Схватился за голову над разъехавшейся версткой в продакшне. Рядом лежит сплющенная резиновая уточка.'
  },
  {
    id: 24,
    name: 'IT-архитектор',
    type: 'property',
    group: 'red',
    groupName: 'IT-департамент & Dev',
    color: '#EF5350',
    price: 240,
    housePrice: 150,
    mortgageValue: 120,
    rents: [46, 120, 360, 850, 1025, 1200],
    icon: '🧙‍♂️',
    iconUrl: '/assets/tiles/office/tech_architect.png',
    description: 'Синьор в свитере с оленями и кружкой «Trust Me, I am an Engineer». Рисует спагетти-микросервисы на доске.'
  },
  {
    id: 25,
    name: 'Самокатчик',
    type: 'property',
    group: 'transport',
    groupName: 'Офисная логистика',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🛴',
    iconUrl: '/assets/tiles/office/scooter_commuter.png',
    description: 'Менеджер в пальто и шлеме лихо мчит по тротуару на жёлтом самокате, лавируя с кожаным портфелем.'
  },
  {
    id: 26,
    name: 'Продакт с канбаном',
    type: 'property',
    group: 'yellow',
    groupName: 'Управление продуктом & Agile',
    color: '#FFCA28',
    price: 260,
    housePrice: 150,
    mortgageValue: 130,
    rents: [50, 130, 390, 900, 1100, 1275],
    icon: '🥑',
    iconUrl: '/assets/tiles/office/product_manager.png',
    description: 'Клеит неоновые стикеры Post-it на канбан-доску со словами «у нас тут pivot», потягивая матча-смузи.'
  },
  {
    id: 27,
    name: 'Скрам-мастер',
    type: 'property',
    group: 'yellow',
    groupName: 'Управление продуктом & Agile',
    color: '#FFCA28',
    price: 260,
    housePrice: 150,
    mortgageValue: 130,
    rents: [50, 130, 390, 900, 1100, 1275],
    icon: '⏱️',
    iconUrl: '/assets/tiles/office/scrum_master.png',
    description: '«Коллеги, у нас ровно 15 минут тайм-бокс!» Свисток на шее и песочные часы наготове на стендапе.'
  },
  {
    id: 28,
    name: 'Завхоз Михалыч',
    type: 'property',
    group: 'utility',
    groupName: 'Сервисные службы офиса',
    color: '#8D6E63',
    price: 150,
    mortgageValue: 75,
    rents: [20, 60, 120, 240],
    icon: '🔧',
    iconUrl: '/assets/tiles/office/facilities_manager.png',
    description: 'В синем халате со связкой ключей и армированным скотчем. Починит любое шатающееся кресло за 5 минут.'
  },
  {
    id: 29,
    name: 'Тимлид на проде',
    type: 'property',
    group: 'yellow',
    groupName: 'Управление продуктом & Agile',
    color: '#FFCA28',
    price: 280,
    housePrice: 150,
    mortgageValue: 140,
    rents: [54, 150, 450, 1000, 1200, 1400],
    icon: '🧯',
    iconUrl: '/assets/tiles/office/teamlead_fire.png',
    description: 'Заливает пеной из огнетушителя пылающий релизный план и горящие баги прямо перед демо заказчику.'
  },
  {
    id: 30,
    name: 'НА КОВЁР К СЕО',
    type: 'go_to_jail',
    targetJailIndex: 10,
    description: '«Срочно зайдите к генеральному!» Отправляйтесь прямо в штрафной кубикл за колонной',
    icon: '🚪',
    iconUrl: '/assets/tiles/office/called_to_ceo.png'
  },

  // --- RIGHT ROW (Tiles 31 to 39) ---
  {
    id: 31,
    name: 'Юрист по NDA',
    type: 'property',
    group: 'green',
    groupName: 'Топ-менеджмент & Директорат',
    color: '#66BB6A',
    price: 300,
    housePrice: 200,
    mortgageValue: 150,
    rents: [60, 150, 450, 1000, 1200, 1400],
    icon: '⚖️',
    iconUrl: '/assets/tiles/office/legal_counsel.png',
    description: 'Вычитывает с лупой 300 страниц NDA мелким шрифтом, вычеркивая всё опасное красной гелевой ручкой.'
  },
  {
    id: 32,
    name: 'Финдир (CFO)',
    type: 'property',
    group: 'green',
    groupName: 'Топ-менеджмент & Директорат',
    color: '#66BB6A',
    price: 300,
    housePrice: 200,
    mortgageValue: 150,
    rents: [60, 150, 450, 1000, 1200, 1400],
    icon: '✂️',
    iconUrl: '/assets/tiles/office/cfo_cuts.png',
    description: 'Ножницами безжалостно режет бюджет праздников и командировок ради рекордных показателей EBITDA.'
  },
  {
    id: 33,
    name: 'Корпоративная Казна',
    type: 'chest',
    description: 'Золотой парашют, годовые дивиденды и акционерные выплаты',
    icon: '🎁',
    iconUrl: '/assets/tiles/office/chest_bonus.png'
  },
  {
    id: 34,
    name: 'Гендиректор (CEO)',
    type: 'property',
    group: 'green',
    groupName: 'Топ-менеджмент & Директорат',
    color: '#66BB6A',
    price: 320,
    housePrice: 200,
    mortgageValue: 160,
    rents: [65, 170, 500, 1100, 1300, 1500],
    icon: '👔',
    iconUrl: '/assets/tiles/office/executive_ceo.png',
    description: 'В безупречном костюме во главе стола: «Рост на 300% к новому кварталу, никаких компромиссов!».'
  },
  {
    id: 35,
    name: 'Майбах шефа',
    type: 'property',
    group: 'transport',
    groupName: 'Офисная логистика',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🚘',
    iconUrl: '/assets/tiles/office/executive_maybach.png',
    description: 'Личный водитель в фуражке держит открытой дверь премиального чёрного седана у входа в высотку.'
  },
  {
    id: 36,
    name: 'Служебный шанс',
    type: 'chance',
    description: 'Тяните карту внутренней проверки и неожиданных кадровых перестановок',
    icon: '💼',
    iconUrl: '/assets/tiles/office/chance_offer.png'
  },
  {
    id: 37,
    name: 'Совет директоров',
    type: 'property',
    group: 'darkblue',
    groupName: 'Бенефициары & Офшоры',
    color: '#5C6BC0',
    price: 350,
    housePrice: 200,
    mortgageValue: 175,
    rents: [70, 175, 500, 1100, 1300, 1500],
    icon: '🦁',
    iconUrl: '/assets/tiles/office/board_chairman.png',
    description: 'Седовласый акционер в бархатном смокинге в панорамном пентхаусе «Федерации» с сигарой и видом на город.'
  },
  {
    id: 38,
    name: 'Сбор на ДР',
    type: 'tax',
    amount: 100,
    description: '«Скидываемся на юбилей по 100 ₽!» Активистка с красным конвертом уже ждёт возле вашего стола',
    icon: '🎂',
    iconUrl: '/assets/tiles/office/tax_birthday.png'
  },
  {
    id: 39,
    name: 'Бенефициар в офшоре',
    type: 'property',
    group: 'darkblue',
    groupName: 'Бенефициары & Офшоры',
    color: '#5C6BC0',
    price: 400,
    housePrice: 200,
    mortgageValue: 200,
    rents: [85, 200, 600, 1400, 1700, 2400],
    icon: '🏝️',
    iconUrl: '/assets/tiles/office/offshore_beneficiary.png',
    description: 'Загорает на палубе белоснежной яхты с бокалом игристого и чемоданом трастовых документов.'
  }
];

const BOARD_TILES_OFFICE_24 = [
  {
    id: 0,
    name: 'ДЕНЬ ЗАРПЛАТЫ',
    type: 'start',
    description: 'Зарплата упала на карту! Получите призовые +200 ₽ при прохождении круга',
    bonus: 200,
    icon: '💳',
    iconUrl: '/assets/tiles/office/start_payday.png'
  },
  {
    id: 1,
    name: 'Строгий вахтёр',
    type: 'property',
    group: 'brown',
    groupName: 'Входная группа & Стажировка',
    color: '#8D6E63',
    price: 60,
    housePrice: 50,
    mortgageValue: 30,
    rents: [10, 30, 90, 270, 400, 550],
    icon: '🛂',
    iconUrl: '/assets/tiles/office/security_turnstile.png',
    description: '«Где ваш пропуск?» Строгий вахтёр со сканером СКУД и чаем в граненом стакане.'
  },
  {
    id: 2,
    name: 'Служебный шанс',
    type: 'chance',
    description: 'Тайный хедхантер и неожиданные повороты корпоративной карьеры',
    icon: '💼',
    iconUrl: '/assets/tiles/office/chance_offer.png'
  },
  {
    id: 3,
    name: 'Стажёр с кофе',
    type: 'property',
    group: 'brown',
    groupName: 'Входная группа & Стажировка',
    color: '#8D6E63',
    price: 80,
    housePrice: 50,
    mortgageValue: 40,
    rents: [14, 40, 120, 360, 500, 650],
    icon: '📋',
    iconUrl: '/assets/tiles/office/intern_stack.png',
    description: 'Балансирует шаткую стопку отчётов А4 и стаканчики кофе, молясь не споткнуться.'
  },
  {
    id: 4,
    name: 'Сбор на ДР',
    type: 'tax',
    amount: 100,
    description: 'Оплатите 100 ₽ на подарок коллеге в общий красный конверт',
    icon: '🎂',
    iconUrl: '/assets/tiles/office/tax_birthday.png'
  },
  {
    id: 5,
    name: 'Сплетница у кулера',
    type: 'property',
    group: 'lightblue',
    groupName: 'Кофе-поинт & Кухня',
    color: '#29B6F6',
    price: 100,
    housePrice: 50,
    mortgageValue: 50,
    rents: [18, 50, 150, 450, 625, 750],
    icon: '💧',
    iconUrl: '/assets/tiles/office/cooler_gossip.png',
    description: 'Знает всё о премиях, сокращениях и романах в опенспейсе раньше всех.'
  },
  {
    id: 6,
    name: 'ДУШНЫЙ КУБИКЛ',
    type: 'jail',
    description: 'Штрафной стол прямо за бетонной колонной. Обычное посещение / Отработка штрафа',
    icon: '🧱',
    iconUrl: '/assets/tiles/office/penalty_cubicle.png'
  },
  {
    id: 7,
    name: 'Секретарша',
    type: 'property',
    group: 'lightblue',
    groupName: 'Кофе-поинт & Кухня',
    color: '#29B6F6',
    price: 120,
    housePrice: 50,
    mortgageValue: 60,
    rents: [22, 60, 180, 500, 700, 900],
    icon: '☕',
    iconUrl: '/assets/tiles/office/coffee_machine.png',
    description: 'Повелительница двойного эспрессо. Единственная, кто умеет перезагружать кофемашину.'
  },
  {
    id: 8,
    name: 'Корпоративная Казна',
    type: 'chest',
    description: 'Тяните карту квартального бонуса или приказа о премировании',
    icon: '🎁',
    iconUrl: '/assets/tiles/office/chest_bonus.png'
  },
  {
    id: 9,
    name: 'HR-интервью',
    type: 'property',
    group: 'pink',
    groupName: 'HR & Корпоративная культура',
    color: '#EC407A',
    price: 140,
    housePrice: 100,
    mortgageValue: 70,
    rents: [26, 70, 200, 550, 750, 950],
    icon: '📋',
    iconUrl: '/assets/tiles/office/hr_interview.png',
    description: '«Кем вы видите себя через 5 лет?» Сканирует резюме рентгеновским взглядом.'
  },
  {
    id: 10,
    name: 'Пятничная пицца',
    type: 'property',
    group: 'pink',
    groupName: 'HR & Корпоративная культура',
    color: '#EC407A',
    price: 160,
    housePrice: 100,
    mortgageValue: 80,
    rents: [30, 80, 220, 600, 800, 1000],
    icon: '🍕',
    iconUrl: '/assets/tiles/office/friday_party.png',
    description: 'Пятница 18:00! Горячая пицца, галстук на лбу и старт корпоративного веселья.'
  },
  {
    id: 11,
    name: 'Сейлз с гонгом',
    type: 'property',
    group: 'orange',
    groupName: 'Отдел продаж & Бухгалтерия',
    color: '#FFA726',
    price: 180,
    housePrice: 100,
    mortgageValue: 90,
    rents: [34, 90, 250, 700, 875, 1050],
    icon: '🔔',
    iconUrl: '/assets/tiles/office/sales_gong.png',
    description: 'Звонит в латунный гонг победы, закрыв миллионный контракт прямо во время перекура.'
  },
  {
    id: 12,
    name: 'ВЫГОРАНИЕ В ЛАУНДЖЕ',
    type: 'free_parking',
    description: 'Мягкий пуфик под фикусом. Бесплатный отдых от бесконечных созвонов в Зуме',
    icon: '🛋️',
    iconUrl: '/assets/tiles/office/lounge_burnout.png'
  },
  {
    id: 13,
    name: 'Главбух Римма',
    type: 'property',
    group: 'orange',
    groupName: 'Отдел продаж & Бухгалтерия',
    color: '#FFA726',
    price: 200,
    housePrice: 100,
    mortgageValue: 100,
    rents: [38, 100, 300, 750, 925, 1100],
    icon: '☕',
    iconUrl: '/assets/tiles/office/chief_accountant.png',
    description: 'Властная хозяйка всех реестров. Спокойно пьёт чай с пряниками, пока все трепещут.'
  },
  {
    id: 14,
    name: 'Служебный шанс',
    type: 'chance',
    description: 'Тяните карту служебных сюрпризов, проверок и срочных задач',
    icon: '💼',
    iconUrl: '/assets/tiles/office/chance_offer.png'
  },
  {
    id: 15,
    name: 'Дежурный админ',
    type: 'property',
    group: 'red',
    groupName: 'IT-департамент & Dev',
    color: '#EF5350',
    price: 220,
    housePrice: 150,
    mortgageValue: 110,
    rents: [42, 110, 330, 800, 975, 1150],
    icon: '🚨',
    iconUrl: '/assets/tiles/office/devops_alert.png',
    description: 'Спит в худи на диване, но мгновенно подрывается при аварийном алерте.'
  },
  {
    id: 16,
    name: 'IT-архитектор',
    type: 'property',
    group: 'red',
    groupName: 'IT-департамент & Dev',
    color: '#EF5350',
    price: 240,
    housePrice: 150,
    mortgageValue: 120,
    rents: [46, 120, 360, 850, 1025, 1200],
    icon: '🧙‍♂️',
    iconUrl: '/assets/tiles/office/tech_architect.png',
    description: 'Синьор в свитере с оленями. Рисует спагетти-микросервисы на маркерной доске.'
  },
  {
    id: 17,
    name: 'Штраф за опоздание',
    type: 'tax',
    amount: 150,
    description: 'Заплатите штраф $150 за нарушение трудового распорядка',
    icon: '⏱️',
    iconUrl: '/assets/tiles/office/tax_late.png'
  },
  {
    id: 18,
    name: 'НА КОВЁР К СЕО',
    type: 'go_to_jail',
    targetJailIndex: 6,
    description: '«Срочно зайдите к генеральному!» Отправляйтесь прямо в штрафной кубикл',
    icon: '🚪',
    iconUrl: '/assets/tiles/office/called_to_ceo.png'
  },
  {
    id: 19,
    name: 'Юрист по NDA',
    type: 'property',
    group: 'green',
    groupName: 'Топ-менеджмент & Директорат',
    color: '#66BB6A',
    price: 300,
    housePrice: 200,
    mortgageValue: 150,
    rents: [60, 150, 450, 1000, 1200, 1400],
    icon: '⚖️',
    iconUrl: '/assets/tiles/office/legal_counsel.png',
    description: 'Вычитывает 300 страниц договора NDA, зачеркивая всё опасное красной ручкой.'
  },
  {
    id: 20,
    name: 'Гендиректор (CEO)',
    type: 'property',
    group: 'green',
    groupName: 'Топ-менеджмент & Директорат',
    color: '#66BB6A',
    price: 320,
    housePrice: 200,
    mortgageValue: 160,
    rents: [65, 170, 500, 1100, 1300, 1500],
    icon: '👔',
    iconUrl: '/assets/tiles/office/executive_ceo.png',
    description: '«Рост прибыли на 300% к новому кварталу, никаких компромиссов!».'
  },
  {
    id: 21,
    name: 'Корпоративная Казна',
    type: 'chest',
    description: 'Поступило решение о выплате внеочередного золотого парашюта',
    icon: '🎁',
    iconUrl: '/assets/tiles/office/chest_bonus.png'
  },
  {
    id: 22,
    name: 'Совет директоров',
    type: 'property',
    group: 'darkblue',
    groupName: 'Бенефициары & Офшоры',
    color: '#5C6BC0',
    price: 350,
    housePrice: 200,
    mortgageValue: 175,
    rents: [70, 175, 500, 1100, 1300, 1500],
    icon: '🦁',
    iconUrl: '/assets/tiles/office/board_chairman.png',
    description: 'Седовласый акционер в панорамном пентхаусе башни Сити с кубинской сигарой.'
  },
  {
    id: 23,
    name: 'Бенефициар в офшоре',
    type: 'property',
    group: 'darkblue',
    groupName: 'Бенефициары & Офшоры',
    color: '#5C6BC0',
    price: 400,
    housePrice: 200,
    mortgageValue: 200,
    rents: [85, 200, 600, 1400, 1700, 2400],
    icon: '🏝️',
    iconUrl: '/assets/tiles/office/offshore_beneficiary.png',
    description: 'Загорает на палубе белоснежной яхты с бокалом шампанского и чемоданом трастов.'
  }
];

module.exports = {
  BOARD_TILES_OFFICE_40,
  BOARD_TILES_OFFICE_24
};
