/**
 * Board configuration for "Панельная романтика: Городской быт" (40 tiles)
 */

const BOARD_TILES_PANEL_40 = [
  // --- BOTTOM ROW (Tiles 0 to 10) ---
  {
    id: 0,
    name: 'ДЕНЬ ПОЛУЧКИ',
    type: 'start',
    description: 'Зарплата упала на карту! Получите призовые +200 ₽ при прохождении круга',
    bonus: 200,
    icon: '💳',
    iconUrl: '/assets/tiles/panel/start_payday.png'
  },
  {
    id: 1,
    name: 'Гаражи «Лада-98»',
    type: 'property',
    group: 'brown',
    groupName: 'Промзона & Гаражи',
    color: '#8D6E63',
    price: 60,
    housePrice: 50,
    mortgageValue: 30,
    rents: [10, 30, 90, 270, 400, 550],
    icon: '🛠️',
    iconUrl: '/assets/tiles/panel/garages_lada.png',
    description: 'Запах бензина, смотровая яма, мангал по выходным и дедушкины банки с огурцами.'
  },
  {
    id: 2,
    name: 'Госуслуги',
    type: 'chest',
    description: 'Тяните талончик с уведомлением из личного кабинета',
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/gosuslugi.png'
  },
  {
    id: 3,
    name: 'Шиномонтажка 24',
    type: 'property',
    group: 'brown',
    groupName: 'Промзона & Гаражи',
    color: '#8D6E63',
    price: 80,
    housePrice: 50,
    mortgageValue: 40,
    rents: [14, 40, 120, 360, 500, 650],
    icon: '🛞',
    iconUrl: '/assets/tiles/panel/tire_service.png',
    description: 'Балансировка колес за 15 минут и крепкий растворимый кофе 3-в-1 в пластиковом стаканчике.'
  },
  {
    id: 4,
    name: 'Квитанция за отопление',
    type: 'tax',
    amount: 200,
    description: 'Оплатите 200 ₽ за отопление в зимний период',
    icon: '🧾',
    iconUrl: '/assets/tiles/panel/tax_heating.png'
  },
  {
    id: 5,
    name: 'Маршрутка №33',
    type: 'property',
    group: 'transport',
    groupName: 'Городской транспорт',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🚐',
    iconUrl: '/assets/tiles/panel/marshrutka_33.png',
    description: '«Передайте за проезд!» Стоячих мест нет, но всегда поместятся ещё шестеро.'
  },
  {
    id: 6,
    name: 'Чебуречная «Дружба»',
    type: 'property',
    group: 'lightblue',
    groupName: 'Быстропит & Рынок',
    color: '#29B6F6',
    price: 100,
    housePrice: 50,
    mortgageValue: 50,
    rents: [18, 50, 150, 450, 625, 750],
    icon: '🥟',
    iconUrl: '/assets/tiles/panel/cheburek_druzhba.png',
    description: 'Хрустящее пузырчатое тесто, обжигающий бульон и верная очередь завсегдатаев.'
  },
  {
    id: 7,
    name: 'Объявления на столбе',
    type: 'chance',
    description: 'Бумажные полоски с телефонами и неожиданные повороты судьбы',
    icon: '📋',
    iconUrl: '/assets/tiles/panel/chance_flyers.png'
  },
  {
    id: 8,
    name: 'Шаурма «На углях»',
    type: 'property',
    group: 'lightblue',
    groupName: 'Быстропит & Рынок',
    color: '#29B6F6',
    price: 100,
    housePrice: 50,
    mortgageValue: 50,
    rents: [18, 50, 150, 450, 625, 750],
    icon: '🌯',
    iconUrl: '/assets/tiles/panel/shaurma_grill.png',
    description: 'Лаваш сырный, соус чесночный, главный оазис ночного голода.'
  },
  {
    id: 9,
    name: 'Овощебаза №4',
    type: 'property',
    group: 'lightblue',
    groupName: 'Быстропит & Рынок',
    color: '#29B6F6',
    price: 120,
    housePrice: 50,
    mortgageValue: 60,
    rents: [22, 60, 180, 500, 700, 900],
    icon: '📦',
    iconUrl: '/assets/tiles/panel/veggie_base.png',
    description: 'Ящики с мандаринами, оптовые мешки картошки и коробки из-под бананов.'
  },
  {
    id: 10,
    name: 'КПЗ РОВД',
    type: 'jail',
    description: 'Обычное посещение / До выяснения обстоятельств. Выход под залог 50 ₽',
    icon: '👮',
    iconUrl: '/assets/tiles/panel/jail_kpz.png'
  },

  // --- RIGHT ROW (Tiles 11 to 20) ---
  {
    id: 11,
    name: 'Радиорынок',
    type: 'property',
    group: 'pink',
    groupName: 'Торговые ряды',
    color: '#EC407A',
    price: 140,
    housePrice: 100,
    mortgageValue: 70,
    rents: [26, 70, 200, 550, 750, 950],
    icon: '📻',
    iconUrl: '/assets/tiles/panel/radio_market.png',
    description: 'Паяльники, редкие микросхемы, б/у телефоны и вопрос: «Девушка, чехол нужен?»'
  },
  {
    id: 12,
    name: 'Горводоканал',
    type: 'property',
    group: 'utility',
    groupName: 'Городские службы',
    color: '#8D6E63',
    price: 150,
    mortgageValue: 75,
    rents: [20, 60, 120, 240],
    icon: '🚰',
    iconUrl: '/assets/tiles/panel/utility_vodokanal.png',
    description: '«Плановые гидравлические испытания. Горячей воды не будет две недели».'
  },
  {
    id: 13,
    name: 'Вещевой рынок',
    type: 'property',
    group: 'pink',
    groupName: 'Торговые ряды',
    color: '#EC407A',
    price: 140,
    housePrice: 100,
    mortgageValue: 70,
    rents: [26, 70, 200, 550, 750, 950],
    icon: '👖',
    iconUrl: '/assets/tiles/panel/clothes_market.png',
    description: 'Примерка джинсов стоя на картонке на морозе за шторкой у палатки.'
  },
  {
    id: 14,
    name: 'Павильон «Мясо-Рыба»',
    type: 'property',
    group: 'pink',
    groupName: 'Торговые ряды',
    color: '#EC407A',
    price: 160,
    housePrice: 100,
    mortgageValue: 80,
    rents: [30, 80, 220, 600, 800, 1000],
    icon: '🥩',
    iconUrl: '/assets/tiles/panel/meat_fish_stall.png',
    description: 'Тётя Валя отрежет лучший кусок без кости, если ласково поздороваться.'
  },
  {
    id: 15,
    name: 'ПАЗик «Дачный»',
    type: 'property',
    group: 'transport',
    groupName: 'Городской транспорт',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🚌',
    iconUrl: '/assets/tiles/panel/pazik_bus.png',
    description: 'Грохочет по ухабам, доверху набит рассадой помидоров и ведрами.'
  },
  {
    id: 16,
    name: 'Хрущёвка-пятиэтажка',
    type: 'property',
    group: 'orange',
    groupName: 'Спальный микрорайон',
    color: '#FFA726',
    price: 180,
    housePrice: 100,
    mortgageValue: 90,
    rents: [34, 90, 250, 700, 875, 1050],
    icon: '🏢',
    iconUrl: '/assets/tiles/panel/khrushchyovka_5fl.png',
    description: 'Уютный зелёный дворик, скрипучие двери, бабушки на страже подъезда.'
  },
  {
    id: 17,
    name: 'Госуслуги',
    type: 'chest',
    description: 'Тяните уведомление из личного кабинета',
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/gosuslugi.png'
  },
  {
    id: 18,
    name: 'Панельная Брежневка',
    type: 'property',
    group: 'orange',
    groupName: 'Спальный микрорайон',
    color: '#FFA726',
    price: 180,
    housePrice: 100,
    mortgageValue: 90,
    rents: [34, 90, 250, 700, 875, 1050],
    icon: '🏢',
    iconUrl: '/assets/tiles/panel/panel_brezhnevka.png',
    description: 'Ковёр на стене для шумоизоляции, балкон с лыжами и санками.'
  },
  {
    id: 19,
    name: 'Девятиэтажка с лифтом',
    type: 'property',
    group: 'orange',
    groupName: 'Спальный микрорайон',
    color: '#FFA726',
    price: 200,
    housePrice: 100,
    mortgageValue: 100,
    rents: [38, 100, 300, 750, 925, 1100],
    icon: '🏢',
    iconUrl: '/assets/tiles/panel/panel_elevator_9fl.png',
    description: 'Лифт на четыре человека с выжженными кнопками и вид на трубы ТЭЦ.'
  },
  {
    id: 20,
    name: 'Лавочка у подъезда',
    type: 'free_parking',
    description: '«Ишь, олигархи поехали!» Бесплатный отдых, щелканье семечек и дворовые сплетни.',
    icon: '👵',
    iconUrl: '/assets/tiles/panel/bench_cat.png'
  },

  // --- TOP ROW (Tiles 21 to 30) ---
  {
    id: 21,
    name: 'Районный ТРК «Планета»',
    type: 'property',
    group: 'red',
    groupName: 'Инфраструктура & Досуг',
    color: '#EF5350',
    price: 220,
    housePrice: 150,
    mortgageValue: 110,
    rents: [42, 110, 330, 800, 975, 1150],
    icon: '🛍️',
    iconUrl: '/assets/tiles/panel/mall_planeta.png',
    description: 'Стеклянные эскалаторы, кинотеатр, фудкорт и островки с чехлами для телефонов.'
  },
  {
    id: 22,
    name: 'Объявления на столбе',
    type: 'chance',
    description: 'Тяните карту городских случайностей',
    icon: '📋',
    iconUrl: '/assets/tiles/panel/chance_flyers.png'
  },
  {
    id: 23,
    name: 'Сетевой «Дискаунтер»',
    type: 'property',
    group: 'red',
    groupName: 'Инфраструктура & Досуг',
    color: '#EF5350',
    price: 220,
    housePrice: 150,
    mortgageValue: 110,
    rents: [42, 110, 330, 800, 975, 1150],
    icon: '🛒',
    iconUrl: '/assets/tiles/panel/discounter_store.png',
    description: 'Жёлтые акционные ценники и тележка с одним вечно заедающим колесом.'
  },
  {
    id: 24,
    name: 'Круглосуточный 24/7',
    type: 'property',
    group: 'red',
    groupName: 'Инфраструктура & Досуг',
    color: '#EF5350',
    price: 240,
    housePrice: 150,
    mortgageValue: 120,
    rents: [46, 120, 360, 850, 1025, 1200],
    icon: '🥫',
    iconUrl: '/assets/tiles/panel/store_24h.png',
    description: 'Главное спасение района ровно в 22:58. Продавщица знает всех по именам.'
  },
  {
    id: 25,
    name: 'Трамвай «Витязь»',
    type: 'property',
    group: 'transport',
    groupName: 'Городской транспорт',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🚋',
    iconUrl: '/assets/tiles/panel/tram_vityaz.png',
    description: 'Звонкий перестук колес на стыках и уютные тёплые печки под сиденьем зимой.'
  },
  {
    id: 26,
    name: 'ЖК «Человейник»',
    type: 'property',
    group: 'yellow',
    groupName: 'Новостройки & Деловой центр',
    color: '#FDD835',
    price: 260,
    housePrice: 150,
    mortgageValue: 130,
    rents: [50, 130, 390, 900, 1100, 1275],
    icon: '🏗️',
    iconUrl: '/assets/tiles/panel/cheloveynik_tower.png',
    description: '25 этажей, студии по 19 м² и звук перфоратора со всех сторон одновременно.'
  },
  {
    id: 27,
    name: 'ЖК «Комфорт Плюс»',
    type: 'property',
    group: 'yellow',
    groupName: 'Новостройки & Деловой центр',
    color: '#FDD835',
    price: 260,
    housePrice: 150,
    mortgageValue: 130,
    rents: [50, 130, 390, 900, 1100, 1275],
    icon: '🚧',
    iconUrl: '/assets/tiles/panel/comfort_gate.png',
    description: 'Двор без машин, шлагбаум, видеонаблюдение и бдительная консьержка.'
  },
  {
    id: 28,
    name: 'Городские электросети',
    type: 'property',
    group: 'utility',
    groupName: 'Городские службы',
    color: '#8D6E63',
    price: 150,
    mortgageValue: 75,
    rents: [20, 60, 120, 240],
    icon: '⚡',
    iconUrl: '/assets/tiles/panel/utility_electric.png',
    description: '«Аварийные работы на подстанции. Доставайте свечи и пауэрбанки».'
  },
  {
    id: 29,
    name: 'Бизнес-центр класса «B-»',
    type: 'property',
    group: 'yellow',
    groupName: 'Новостройки & Деловой центр',
    color: '#FDD835',
    price: 280,
    housePrice: 150,
    mortgageValue: 140,
    rents: [55, 140, 420, 950, 1150, 1350],
    icon: '🏢',
    iconUrl: '/assets/tiles/panel/business_center.png',
    description: 'Офисы оптовых компаний, коворкинг у лифта и вечная очередь за ланчем.'
  },
  {
    id: 30,
    name: 'Наряд ППС',
    type: 'go_to_jail',
    targetJailIndex: 10,
    description: '«Гражданин, предъявите документики!» Отправляйтесь прямиком в КПЗ!',
    icon: '🚨',
    iconUrl: '/assets/tiles/panel/police_patrol.png'
  },

  // --- LEFT ROW (Tiles 31 to 39) ---
  {
    id: 31,
    name: 'Кофейня спешелти',
    type: 'property',
    group: 'green',
    groupName: 'Модный центр',
    color: '#66BB6A',
    price: 300,
    housePrice: 200,
    mortgageValue: 150,
    rents: [60, 150, 450, 1000, 1200, 1400],
    icon: '☕',
    iconUrl: '/assets/tiles/panel/specialty_coffee.png',
    description: 'Фильтр-кофе на зерне из Эфиопии, сырники, макбуки и винтажная кирпичная кладка.'
  },
  {
    id: 32,
    name: 'Крафтовый бар',
    type: 'property',
    group: 'green',
    groupName: 'Модный центр',
    color: '#66BB6A',
    price: 300,
    housePrice: 200,
    mortgageValue: 150,
    rents: [60, 150, 450, 1000, 1200, 1400],
    icon: '🍻',
    iconUrl: '/assets/tiles/panel/craft_bar.png',
    description: 'Неоновая вывеска в подвале, 40 кранов IPA и громкие споры о футболе и музыке.'
  },
  {
    id: 33,
    name: 'Госуслуги',
    type: 'chest',
    description: 'Поступило новое персональное уведомление',
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/gosuslugi.png'
  },
  {
    id: 34,
    name: 'Лофт на заводе',
    type: 'property',
    group: 'green',
    groupName: 'Модный центр',
    color: '#66BB6A',
    price: 320,
    housePrice: 200,
    mortgageValue: 160,
    rents: [65, 170, 500, 1100, 1300, 1500],
    icon: '🏭',
    iconUrl: '/assets/tiles/panel/loft_factory.png',
    description: 'Арт-пространство, выставки современного искусства и бутики локальных брендов.'
  },
  {
    id: 35,
    name: 'Кольцевая электричка',
    type: 'property',
    group: 'transport',
    groupName: 'Городской транспорт',
    color: '#78909C',
    price: 200,
    mortgageValue: 100,
    rents: [25, 50, 100, 200],
    icon: '🚆',
    iconUrl: '/assets/tiles/panel/electric_train.png',
    description: 'Запах шпал, стук колес и продавцы супер-клея, фонариков и носков прямо в вагоне.'
  },
  {
    id: 36,
    name: 'Объявления на столбе',
    type: 'chance',
    description: 'Тяните карту уличных приключений',
    icon: '📋',
    iconUrl: '/assets/tiles/panel/chance_flyers.png'
  },
  {
    id: 37,
    name: 'Сталинская высотка',
    type: 'property',
    group: 'darkblue',
    groupName: 'Элитный фонд',
    color: '#5C6BC0',
    price: 350,
    housePrice: 200,
    mortgageValue: 175,
    rents: [70, 175, 500, 1100, 1300, 1500],
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/stalinka_tower.png',
    description: 'Потолки 3.5 метра, дубовый наборный паркет и монументальный вид на набережную.'
  },
  {
    id: 38,
    name: 'Взнос на капремонт',
    type: 'tax',
    amount: 100,
    description: 'Оплатите сбор на ремонт фасада, запланированный на 2049 год',
    icon: '🔨',
    iconUrl: '/assets/tiles/panel/tax_caprepair.png'
  },
  {
    id: 39,
    name: 'Дореволюционный особняк',
    type: 'property',
    group: 'darkblue',
    groupName: 'Элитный фонд',
    color: '#5C6BC0',
    price: 400,
    housePrice: 200,
    mortgageValue: 200,
    rents: [85, 200, 600, 1400, 1700, 2400],
    icon: '🏰',
    iconUrl: '/assets/tiles/panel/mansion_manor.png',
    description: 'Закрытый двор с вековыми липами, охрана, кованые ворота и тишина в самом центре.'
  }
];

const BOARD_TILES_PANEL_24 = [
  {
    id: 0,
    name: 'ДЕНЬ ПОЛУЧКИ',
    type: 'start',
    description: 'Зарплата упала на карту! Получите призовые +200 ₽ при прохождении круга',
    bonus: 200,
    icon: '💳',
    iconUrl: '/assets/tiles/panel/start_payday.png'
  },
  {
    id: 1,
    name: 'Гаражи «Лада-98»',
    type: 'property',
    group: 'brown',
    groupName: 'Промзона & Гаражи',
    color: '#8D6E63',
    price: 60,
    housePrice: 50,
    mortgageValue: 30,
    rents: [10, 30, 90, 270, 400, 550],
    icon: '🛠️',
    iconUrl: '/assets/tiles/panel/garages_lada.png',
    description: 'Запах бензина, смотровая яма, мангал по выходным и дедушкины банки с огурцами.'
  },
  {
    id: 2,
    name: 'Объявления на столбе',
    type: 'chance',
    description: 'Бумажные полоски с телефонами и неожиданные повороты судьбы',
    icon: '📋',
    iconUrl: '/assets/tiles/panel/chance_flyers.png'
  },
  {
    id: 3,
    name: 'Шиномонтажка 24',
    type: 'property',
    group: 'brown',
    groupName: 'Промзона & Гаражи',
    color: '#8D6E63',
    price: 80,
    housePrice: 50,
    mortgageValue: 40,
    rents: [14, 40, 120, 360, 500, 650],
    icon: '🛞',
    iconUrl: '/assets/tiles/panel/tire_service.png',
    description: 'Балансировка колес за 15 минут и крепкий растворимый кофе 3-в-1.'
  },
  {
    id: 4,
    name: 'Квитанция за отопление',
    type: 'tax',
    amount: 100,
    description: 'Оплатите 100 ₽ за отопление в зимний период',
    icon: '🧾',
    iconUrl: '/assets/tiles/panel/tax_heating.png'
  },
  {
    id: 5,
    name: 'Чебуречная «Дружба»',
    type: 'property',
    group: 'lightblue',
    groupName: 'Быстропит & Рынок',
    color: '#29B6F6',
    price: 100,
    housePrice: 50,
    mortgageValue: 50,
    rents: [18, 50, 150, 450, 625, 750],
    icon: '🥟',
    iconUrl: '/assets/tiles/panel/cheburek_druzhba.png',
    description: 'Хрустящее пузырчатое тесто, обжигающий бульон и верная очередь завсегдатаев.'
  },
  {
    id: 6,
    name: 'КПЗ РОВД',
    type: 'jail',
    description: 'Обычное посещение / До выяснения обстоятельств',
    icon: '👮',
    iconUrl: '/assets/tiles/panel/jail_kpz.png'
  },
  {
    id: 7,
    name: 'Шаурма «На углях»',
    type: 'property',
    group: 'lightblue',
    groupName: 'Быстропит & Рынок',
    color: '#29B6F6',
    price: 120,
    housePrice: 50,
    mortgageValue: 60,
    rents: [22, 60, 180, 500, 700, 900],
    icon: '🌯',
    iconUrl: '/assets/tiles/panel/shaurma_grill.png',
    description: 'Лаваш сырный, соус чесночный, главный оазис ночного голода.'
  },
  {
    id: 8,
    name: 'Госуслуги',
    type: 'chest',
    description: 'Тяните уведомление из личного кабинета',
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/gosuslugi.png'
  },
  {
    id: 9,
    name: 'Радиорынок',
    type: 'property',
    group: 'pink',
    groupName: 'Торговые ряды',
    color: '#EC407A',
    price: 140,
    housePrice: 100,
    mortgageValue: 70,
    rents: [26, 70, 200, 550, 750, 950],
    icon: '📻',
    iconUrl: '/assets/tiles/panel/radio_market.png',
    description: 'Паяльники, редкие микросхемы, б/у телефоны и чехлы.'
  },
  {
    id: 10,
    name: 'Павильон «Мясо-Рыба»',
    type: 'property',
    group: 'pink',
    groupName: 'Торговые ряды',
    color: '#EC407A',
    price: 160,
    housePrice: 100,
    mortgageValue: 80,
    rents: [30, 80, 220, 600, 800, 1000],
    icon: '🥩',
    iconUrl: '/assets/tiles/panel/meat_fish_stall.png',
    description: 'Тётя Валя отрежет лучший кусок без кости.'
  },
  {
    id: 11,
    name: 'Хрущёвка-пятиэтажка',
    type: 'property',
    group: 'orange',
    groupName: 'Спальный микрорайон',
    color: '#FFA726',
    price: 180,
    housePrice: 100,
    mortgageValue: 90,
    rents: [34, 90, 250, 700, 875, 1050],
    icon: '🏢',
    iconUrl: '/assets/tiles/panel/khrushchyovka_5fl.png',
    description: 'Уютный зелёный дворик, скрипучие двери, бабушки на страже подъезда.'
  },
  {
    id: 12,
    name: 'Лавочка у подъезда',
    type: 'free_parking',
    description: '«Ишь, олигархи поехали!» Бесплатный отдых, щелканье семечек и дворовые сплетни.',
    icon: '👵',
    iconUrl: '/assets/tiles/panel/bench_cat.png'
  },
  {
    id: 13,
    name: 'Панельная Брежневка',
    type: 'property',
    group: 'orange',
    groupName: 'Спальный микрорайон',
    color: '#FFA726',
    price: 200,
    housePrice: 100,
    mortgageValue: 100,
    rents: [38, 100, 300, 750, 925, 1100],
    icon: '🏢',
    iconUrl: '/assets/tiles/panel/panel_brezhnevka.png',
    description: 'Ковёр на стене для шумоизоляции, балкон с лыжами и санками.'
  },
  {
    id: 14,
    name: 'Объявления на столбе',
    type: 'chance',
    description: 'Тяните карту городских случайностей',
    icon: '📋',
    iconUrl: '/assets/tiles/panel/chance_flyers.png'
  },
  {
    id: 15,
    name: 'Сетевой «Дискаунтер»',
    type: 'property',
    group: 'red',
    groupName: 'Инфраструктура & Досуг',
    color: '#EF5350',
    price: 220,
    housePrice: 150,
    mortgageValue: 110,
    rents: [42, 110, 330, 800, 975, 1150],
    icon: '🛒',
    iconUrl: '/assets/tiles/panel/discounter_store.png',
    description: 'Жёлтые акционные ценники и тележка с одним вечно заедающим колесом.'
  },
  {
    id: 16,
    name: 'Круглосуточный 24/7',
    type: 'property',
    group: 'red',
    groupName: 'Инфраструктура & Досуг',
    color: '#EF5350',
    price: 240,
    housePrice: 150,
    mortgageValue: 120,
    rents: [46, 120, 360, 850, 1025, 1200],
    icon: '🥫',
    iconUrl: '/assets/tiles/panel/store_24h.png',
    description: 'Главное спасение района ровно в 22:58.'
  },
  {
    id: 17,
    name: 'Взнос на капремонт',
    type: 'tax',
    amount: 150,
    description: 'Оплатите сбор на ремонт фасада $150',
    icon: '🔨',
    iconUrl: '/assets/tiles/panel/tax_caprepair.png'
  },
  {
    id: 18,
    name: 'Наряд ППС',
    type: 'go_to_jail',
    targetJailIndex: 6,
    description: '«Гражданин, предъявите документики!» Отправляйтесь прямиком в КПЗ!',
    icon: '🚨',
    iconUrl: '/assets/tiles/panel/police_patrol.png'
  },
  {
    id: 19,
    name: 'Кофейня спешелти',
    type: 'property',
    group: 'green',
    groupName: 'Модный центр',
    color: '#66BB6A',
    price: 300,
    housePrice: 200,
    mortgageValue: 150,
    rents: [60, 150, 450, 1000, 1200, 1400],
    icon: '☕',
    iconUrl: '/assets/tiles/panel/specialty_coffee.png',
    description: 'Фильтр-кофе на зерне из Эфиопии, сырники, макбуки.'
  },
  {
    id: 20,
    name: 'Крафтовый бар',
    type: 'property',
    group: 'green',
    groupName: 'Модный центр',
    color: '#66BB6A',
    price: 320,
    housePrice: 200,
    mortgageValue: 160,
    rents: [65, 170, 500, 1100, 1300, 1500],
    icon: '🍻',
    iconUrl: '/assets/tiles/panel/craft_bar.png',
    description: 'Неоновая вывеска в подвале, 40 кранов IPA.'
  },
  {
    id: 21,
    name: 'Госуслуги',
    type: 'chest',
    description: 'Поступило новое персональное уведомление',
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/gosuslugi.png'
  },
  {
    id: 22,
    name: 'Сталинская высотка',
    type: 'property',
    group: 'darkblue',
    groupName: 'Элитный фонд',
    color: '#5C6BC0',
    price: 350,
    housePrice: 200,
    mortgageValue: 175,
    rents: [70, 175, 500, 1100, 1300, 1500],
    icon: '🏛️',
    iconUrl: '/assets/tiles/panel/stalinka_tower.png',
    description: 'Потолки 3.5 метра, дубовый наборный паркет и вид на набережную.'
  },
  {
    id: 23,
    name: 'Дореволюционный особняк',
    type: 'property',
    group: 'darkblue',
    groupName: 'Элитный фонд',
    color: '#5C6BC0',
    price: 400,
    housePrice: 200,
    mortgageValue: 200,
    rents: [85, 200, 600, 1400, 1700, 2400],
    icon: '🏰',
    iconUrl: '/assets/tiles/panel/mansion_manor.png',
    description: 'Закрытый двор с вековыми липами, охрана, кованые ворота.'
  }
];

module.exports = {
  BOARD_TILES_PANEL_40,
  BOARD_TILES_PANEL_24
};

